# Generated by Django 4.1.7 on 2023-03-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="auction", name="description",),
    ]
