# Generated by Django 4.1.7 on 2023-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_remove_auction_url_image_auction_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="category",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
