# Generated by Django 4.1.7 on 2023-03-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctions"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctions",
            name="bid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
