# Generated by Django 4.1.7 on 2023-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_watchlist_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="watchlist",
            field=models.BooleanField(default=False),
        ),
    ]
