# Generated by Django 4.1.7 on 2023-03-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid", old_name="auction_id", new_name="auction",
        ),
        migrations.RenameField(model_name="bid", old_name="user_id", new_name="user",),
    ]
