# Generated by Django 4.1.7 on 2023-03-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auctions_bid"),
    ]

    operations = [
        migrations.RenameModel(old_name="Auctions", new_name="Auction",),
    ]
