# Generated by Django 4.1.7 on 2023-03-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_auction_id_bid_auction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid", old_name="auction", new_name="auction_id",
        ),
        migrations.RenameField(model_name="bid", old_name="user", new_name="user_id",),
    ]
