# Generated by Django 4.1.7 on 2023-03-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_auction_bid_auction_active_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Auction",),
    ]
