# Generated by Django 4.1.7 on 2023-03-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_rename_auction_bid_auction_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="start_bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
